version: "3"
services:  
  yarn:
    container_name: nd_yarn
    image: node:10-stretch
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: >
      bash -xc 'npm i -g cross-env ; cd /app ; yarn ; yarn watch'
